#!/bin/bash
# fstab-rev2.sh
# Auto-generate fstab.generated tanpa tanya user,
# sesuai rule default mount point dan opsi.

output="fstab.generated"
echo "# Generated by fstab-rev2.sh on $(date)" > "$output"
echo "# <file system> <mount point> <type> <options> <dump> <pass>" >> "$output"
echo "" >> "$output"

# Counter untuk tiap tipe
vfat_cnt=0
btrfs_cnt=0
ext4_cnt=0

# Parse blkid per record
sudo blkid -o export | awk -v RS= '
  /^DEVNAME/ {
    dev=""; uuid=""; fstype="";
    for(i=1;i<=NF;i++){
      split($i,a,"=");
      if(a[1]=="DEVNAME") dev=a[2]
      if(a[1]=="UUID")    uuid=a[2]
      if(a[1]=="TYPE")    fstype=a[2]
    }
    if(uuid && fstype) print dev, uuid, fstype
  }
' | while read dev uuid fstype; do
  case "$fstype" in
    vfat)
      vfat_cnt=$((vfat_cnt+1))
      if [ "$vfat_cnt" -eq 1 ]; then
        mp="/boot/efi"
        opts="umask=0077"
        dump=0; pass=0
      else
        # partisi vfat kedua—skip atau mount ke /mnt
        continue
      fi
      ;;
    btrfs)
      btrfs_cnt=$((btrfs_cnt+1))
      if [ "$btrfs_cnt" -eq 1 ]; then
        mp="/"
        opts="defaults,subvol=@"
        dump=0; pass=1
      else
        continue
      fi
      ;;
    ext4)
      ext4_cnt=$((ext4_cnt+1))
      if [ "$ext4_cnt" -eq 1 ]; then
        mp="/data"
        opts="defaults"
        dump=0; pass=2
      else
        continue
      fi
      ;;
    swap)
      mp="none"
      opts="sw"
      dump=0; pass=0
      ;;
    *)
      # skip tipe lain
      continue
      ;;
  esac

  echo "UUID=$uuid  $mp  $fstype  $opts  $dump  $pass" >> "$output"
done

# Tambahkan swap dari swapon jika belum ada
sudo swapon --show=NAME,UUID | tail -n +2 | awk '{print $2}' | while read sw_uuid; do
  grep -q "UUID=$sw_uuid" "$output" || \
    echo "UUID=$sw_uuid  none  swap  sw  0  0" >> "$output"
done

# Tampilkan hasil
echo ""
echo "✅ Selesai! Isi $output:"
echo "-------------------------"
cat "$output"
